package cn.zhucongqi.tiger.base.model;

import com.jfinal.ext.plugin.activerecord.ModelExt;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by jfinal-ext3, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseReportTigerDeviceToken<M extends BaseReportTigerDeviceToken<M>> extends ModelExt<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setUuid(java.lang.String uuid) {
		set("uuid", uuid);
		return (M)this;
	}
	
	public java.lang.String getUuid() {
		return getStr("uuid");
	}

	public M setToken(java.lang.String token) {
		set("token", token);
		return (M)this;
	}
	
	public java.lang.String getToken() {
		return getStr("token");
	}

	public M setTimeout(java.math.BigInteger timeout) {
		set("timeout", timeout);
		return (M)this;
	}
	
	public java.math.BigInteger getTimeout() {
		return get("timeout");
	}

}
