/*
 * Copyright 2018 Jobsz
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
*/
package cn.zhucongqi.tiger.base.model;

import com.jfinal.ext.plugin.activerecord.ModelExt;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by jfinal-ext3, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseReportTigerAppSecretKeys<M extends BaseReportTigerAppSecretKeys<M>> extends ModelExt<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setPackageName(java.lang.String packageName) {
		set("package_name", packageName);
		return (M)this;
	}
	
	public java.lang.String getPackageName() {
		return getStr("package_name");
	}

	public M setBundle(java.lang.String bundle) {
		set("bundle", bundle);
		return (M)this;
	}
	
	public java.lang.String getBundle() {
		return getStr("bundle");
	}

	public M setAppkey(java.lang.String appkey) {
		set("appkey", appkey);
		return (M)this;
	}
	
	public java.lang.String getAppkey() {
		return getStr("appkey");
	}

	public M setSecretkey(java.lang.String secretkey) {
		set("secretkey", secretkey);
		return (M)this;
	}
	
	public java.lang.String getSecretkey() {
		return getStr("secretkey");
	}

	public M setSecretkeysalt(java.lang.String secretkeysalt) {
		set("secretkeysalt", secretkeysalt);
		return (M)this;
	}
	
	public java.lang.String getSecretkeysalt() {
		return getStr("secretkeysalt");
	}

}
