package cn.zhucongqi.tiger.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTigerMappingInfo<M extends BaseTigerMappingInfo<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setAppid(java.math.BigInteger appid) {
		set("appid", appid);
	}

	public java.math.BigInteger getAppid() {
		return get("appid");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setIntro(java.lang.String intro) {
		set("intro", intro);
	}

	public java.lang.String getIntro() {
		return get("intro");
	}

	public void setCdate(java.math.BigInteger cdate) {
		set("cdate", cdate);
	}

	public java.math.BigInteger getCdate() {
		return get("cdate");
	}

}
