package cn.zhucongqi.tiger.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTigerAppSecretKeys<M extends BaseTigerAppSecretKeys<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setPackageName(java.lang.String packageName) {
		set("package_name", packageName);
	}

	public java.lang.String getPackageName() {
		return get("package_name");
	}

	public void setBundle(java.lang.String bundle) {
		set("bundle", bundle);
	}

	public java.lang.String getBundle() {
		return get("bundle");
	}

	public void setAppkey(java.lang.String appkey) {
		set("appkey", appkey);
	}

	public java.lang.String getAppkey() {
		return get("appkey");
	}

	public void setSecretkey(java.lang.String secretkey) {
		set("secretkey", secretkey);
	}

	public java.lang.String getSecretkey() {
		return get("secretkey");
	}

	public void setSecretkeysalt(java.lang.String secretkeysalt) {
		set("secretkeysalt", secretkeysalt);
	}

	public java.lang.String getSecretkeysalt() {
		return get("secretkeysalt");
	}

}
