/*
 * Copyright 2018 Jobsz
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
*/
package cn.zhucongqi.tiger.base.model;

import com.jfinal.ext.plugin.activerecord.ModelExt;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by jfinal-ext3, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseReportTigerDeviceToken<M extends BaseReportTigerDeviceToken<M>> extends ModelExt<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setUuid(java.lang.String uuid) {
		set("uuid", uuid);
		return (M)this;
	}
	
	public java.lang.String getUuid() {
		return getStr("uuid");
	}

	public M setToken(java.lang.String token) {
		set("token", token);
		return (M)this;
	}
	
	public java.lang.String getToken() {
		return getStr("token");
	}

	public M setTimeout(java.math.BigInteger timeout) {
		set("timeout", timeout);
		return (M)this;
	}
	
	public java.math.BigInteger getTimeout() {
		return get("timeout");
	}

}
