package cn.zhucongqi.tiger.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTigerDeviceToken<M extends BaseTigerDeviceToken<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setTimeout(java.math.BigInteger timeout) {
		set("timeout", timeout);
	}

	public java.math.BigInteger getTimeout() {
		return get("timeout");
	}

}
