package cn.zhucongqi.tiger.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tiger_app_secret_keys", "id", TigerAppSecretKeys.class);
		arp.addMapping("tiger_device_token", "id", TigerDeviceToken.class);
		arp.addMapping("tiger_mapping_info", "id", TigerMappingInfo.class);
	}
}

