package cn.zhucongqi.tiger.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by jfinal-ext3, do not modify this file.
 * The jfinal-ext3's JFinalConfigExt will load this file silently.
 */
public class MYSQL_MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("report_tiger_app_secret_keys", "id", ReportTigerAppSecretKeys.class);
		arp.addMapping("report_tiger_device_token", "id", ReportTigerDeviceToken.class);
		arp.addMapping("report_tiger_mapping_info", "id", ReportTigerMappingInfo.class);
	}
}

