package cn.zhucongqi.tiger.model;

import cn.zhucongqi.tiger.base.model.BaseReportTigerAppSecretKeys;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReportTigerAppSecretKeys extends BaseReportTigerAppSecretKeys<ReportTigerAppSecretKeys> {
	public static final ReportTigerAppSecretKeys dao = new ReportTigerAppSecretKeys().dao();
}
