package cn.zhucongqi.tiger.model;

import cn.zhucongqi.tiger.base.model.BaseReportTigerMappingInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReportTigerMappingInfo extends BaseReportTigerMappingInfo<ReportTigerMappingInfo> {
	public static final ReportTigerMappingInfo dao = new ReportTigerMappingInfo().dao();
}
