package cn.zhucongqi.tiger.model;

import cn.zhucongqi.tiger.base.model.BaseReportTigerDeviceToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReportTigerDeviceToken extends BaseReportTigerDeviceToken<ReportTigerDeviceToken> {
	public static final ReportTigerDeviceToken dao = new ReportTigerDeviceToken().dao();
}
