package cn.zhucongqi.tiger.model;

import cn.zhucongqi.tiger.base.model.BaseTigerDeviceToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TigerDeviceToken extends BaseTigerDeviceToken<TigerDeviceToken> {
	public static final TigerDeviceToken dao = new TigerDeviceToken();
	public static final String table = "tiger_device_token";
}
