package cn.zhucongqi.tiger.model;

import cn.zhucongqi.tiger.base.model.BaseTigerAppSecretKeys;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TigerAppSecretKeys extends BaseTigerAppSecretKeys<TigerAppSecretKeys> {
	public static final TigerAppSecretKeys dao = new TigerAppSecretKeys();
	public static final String table = "tiger_app_secret_keys";
}
