package cn.zhucongqi.tiger.model;

import cn.zhucongqi.tiger.base.model.BaseTigerMappingInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TigerMappingInfo extends BaseTigerMappingInfo<TigerMappingInfo> {
	public static final TigerMappingInfo dao = new TigerMappingInfo();
	public static final String table = "tiger_mapping_info";
}
